// Generated by CoffeeScript 1.8.0
var InputError;

InputError = (function() {
  var Err, instance;

  function InputError() {}

  instance = null;

  InputError.get = function() {
    if (instance == null) {
      instance = new Err();
    }
    return instance;
  };

  Err = (function() {
    function Err() {}

    Err.prototype.isArrayOfNums = function(X) {
      return X.constructor === Array && _.every(X, function(n) {
        return isNaN(n);
      });
    };

    Err.prototype.displayErrorMessage = function(svg, msg) {
      var errorContainer, errorImage, errorText;
      errorContainer = $('<div class="rhtml-error-container">');
      errorImage = $('<img width="32px" height="32px" src="https://s3-ap-southeast-2.amazonaws.com/kyle-public-numbers-assets/htmlwidgets/CroppedImage/error_128.png"/>');
      errorText = $('<span>').html(msg.toString());
      errorContainer.append(errorImage);
      errorContainer.append(errorText);
      $(svg).empty();
      $(svg).append(errorContainer);
      throw new Error(msg);
    };

    return Err;

  })();

  return InputError;

})();
