// Generated by CoffeeScript 1.8.0
var PlotColors;

PlotColors = (function() {
  function PlotColors(plotData) {
    var group, i, newColor;
    this.plotData = plotData;
    group = this.plotData.group;
    this.plotData.legendGroups = [];
    this.groupToColorMap = {};
    if (group != null) {
      i = 0;
      while (i < group.length) {
        if (!(_.some(this.plotData.legendGroups, function(e) {
          return e.text === group[i];
        }))) {
          newColor = this.getNewColor(this.plotData.cIndex);
          this.plotData.cIndex++;
          this.plotData.legendGroups.push({
            text: group[i],
            color: newColor,
            r: this.plotData.legendDim.ptRadius,
            anchor: 'start'
          });
          this.groupToColorMap[group[i]] = newColor;
        }
        i++;
      }
    }
  }

  PlotColors.prototype.getColorFromGroup = function(group) {
    return this.groupToColorMap[group];
  };

  PlotColors.prototype.getNewColor = function(index) {
    return this.plotData.colorWheel[index % this.plotData.colorWheel.length];
  };

  PlotColors.prototype.getColor = function(i) {
    if ((this.plotData.group != null) && this.plotData.group instanceof Array) {
      return this.getColorFromGroup(this.plotData.group[i]);
    } else {
      return this.getNewColor(0);
    }
  };

  return PlotColors;

})();
