// Generated by CoffeeScript 1.8.0
var RectPlot;

RectPlot = (function() {
  var _calcViewBoxDim;

  function RectPlot(width, height) {}

  RectPlot.prototype.draw = function() {};

  _calcViewBoxDim = function(X, Y, width, height) {
    return {
      width: width / 2,
      height: height / 2,
      rangeX: Math.max.apply(null, X) - Math.min.apply(null, X),
      rangeY: Math.max.apply(null, Y) - Math.min.apply(null, Y)
    };
  };

  return RectPlot;

})();
