// Generated by CoffeeScript 1.8.0
'use strict';
HTMLWidgets.widget({
  name: 'rhtmlTemplate',
  type: 'output',
  resize: function(el, width, height, instance) {
    return instance.resize(width, height);
  },
  initialize: function(el, width, height) {
    return new Template(el, width, height);
  },
  renderValue: function(el, config, instance) {
    var err, errorHandler, readableError;
    try {
      if (_.isString(config)) {
        config = JSON.parse(config);
      }
    } catch (_error) {
      err = _error;
      readableError = new Error("Template error : Cannot parse 'settingsJsonString': " + err);
      console.error(readableError);
      errorHandler = new DisplayError(el, readableError);
      errorHandler.draw();
      throw new Error(err);
    }
    delete config['width'];
    delete config['height'];
    try {
      instance.setConfig(config);
      return instance.draw();
    } catch (_error) {
      err = _error;
      console.error(err.stack);
      errorHandler = new DisplayError(el, err);
      errorHandler.draw();
      throw new Error(err);
    }
  }
});
