// Generated by CoffeeScript 1.8.0
'use strict';
HTMLWidgets.widget({
  name: 'rhtmlLabeledScatter',
  type: 'output',
  initialize: function(el, width, height) {
    console.log('initialize called');
    return new LabeledScatter(width, height);
  },
  resize: function(el, width, height, instance) {
    console.log('resize called');
    instance.resize(el, width, height);
    return instance;
  },
  renderValue: function(el, params, instance) {
    console.log('renderValue called');
    return instance.draw(params, el);
  }
});
