// Generated by CoffeeScript 1.8.0
'use strict';
HTMLWidgets.widget({
  name: 'rhtmlLabeledScatter',
  type: 'output',
  factory: function(el, width, height, stateChanged) {
    var instance;
    console.log('rhtmlLabeledScatter: factory called');
    instance = new LabeledScatter(width, height, stateChanged);
    return {
      resize: function(width, height) {
        console.log('rhtmlLabeledScatter: resize called');
        return instance.resize(el, width, height);
      },
      renderValue: function(params, state) {
        console.log('rhtmlLabeledScatter: renderValue called');
        return instance.draw(params, el, state);
      },
      labeledScatter: instance
    };
  }
});
