// Generated by CoffeeScript 1.8.0
var SvgUtils;

SvgUtils = (function() {
  var SU, instance;

  function SvgUtils() {}

  instance = null;

  SvgUtils.get = function() {
    if (instance == null) {
      instance = new SU();
    }
    return instance;
  };

  SU = (function() {
    function SU() {}

    SU.prototype.setSvgBBoxWidthAndHeight = function(arrayLen, dataArray, svgArray) {
      var i;
      i = 0;
      while (i < arrayLen) {
        dataArray[i].width = svgArray[0][i].getBBox().width;
        dataArray[i].height = svgArray[0][i].getBBox().height;
        i++;
      }
    };

    SU.prototype.getSvgTextArrayMaxHeight = function(svg) {};

    SU.prototype.getAxisMarkerTextMaxWidth = function() {};

    return SU;

  })();

  return SvgUtils;

})();
