// Generated by CoffeeScript 1.8.0
var TrendLine,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

TrendLine = (function() {
  function TrendLine(pts) {
    this.pts = pts;
    this.getTrendLines = __bind(this.getTrendLines, this);
    this.createLineArray = __bind(this.createLineArray, this);
    this.linePts = {};
    _.map(this.pts, (function(_this) {
      return function(pt) {
        if (_this.linePts[pt.group] == null) {
          _this.linePts[pt.group] = [];
        }
        return _this.linePts[pt.group].push({
          x: pt.x,
          y: pt.y,
          z: pt.r
        });
      };
    })(this));
    console.log(this.linePts);
    this.createLineArray();
  }

  TrendLine.prototype.createLineArray = function() {
    return this.lines = {};
  };

  TrendLine.prototype.getTrendLines = function() {
    return this.lines;
  };

  return TrendLine;

})();
