// Generated by CoffeeScript 1.8.0
var TrendLines,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

TrendLines = (function() {
  function TrendLines(X, Y, Z, group) {
    var i, x, _i, _len, _ref;
    this.X = X;
    this.Y = Y;
    this.Z = Z;
    this.group = group;
    this.getTrendLines = __bind(this.getTrendLines, this);
    if (!(this.X.length === this.Y.length && this.X.length === this.Z.length && this.X.length === this.group.length)) {
      throw new Error('Given X, Y, Z, group unequal lengths!');
    }
    this.lines = {};
    _ref = this.X;
    for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
      x = _ref[i];
      if (lines[this.group[i]] == null) {
        lines[this.group[i]] = [];
      }
      this.line.push([]);
    }
  }

  TrendLines.prototype.getTrendLines = function() {
    return this.lines;
  };

  return TrendLines;

})();
