// Generated by CoffeeScript 1.8.0
var Utils;

Utils = (function() {
  var U, instance;

  function Utils() {}

  instance = null;

  Utils.get = function() {
    if (instance == null) {
      instance = new U();
    }
    return instance;
  };

  U = (function() {
    function U() {}

    U.prototype.isNum = function(num) {
      return (num != null) && typeof num === 'number';
    };

    U.prototype.isArr = function(arr) {
      return (arr != null) && arr instanceof Array;
    };

    return U;

  })();

  return Utils;

})();
