#NB auto generated by gulp build from theSrc/features/features.json

library(devtools)
install_github("NumbersInternational/rhtmlLabeledScatter", auth_token="d8d69ec8f7941263cf1f9d1105292e698b803fce")
#Feature 1
##Scenario 1 - Initial State Green
###This demonstrates a common scenario for your widget.
###In this case the initialState is set to green.
###In this case try clicking the squares and watching the stateListener get fired.

rhtmlLabeledScatter::LabeledScatter('{"width":400,"height":400}')

##Scenario 1 - Initial State Blue
###This demonstrates a common scenario for your widget 
###In this case the initialState is set to blue.
###In this case try clicking the squares and watching the stateListener get fired.

rhtmlLabeledScatter::LabeledScatter('{"width":400,"height":400}')

#Feature 2 - typically this is different from Feature 1
##Scenario 1 - No initial state
###This demonstrates a common scenario for your widget 
###In this case nothing has been done for this example, it just shows how to setup a second feature in the feature.json

rhtmlLabeledScatter::LabeledScatter('{"width":400,"height":400}')

#Error Handling
##Bad JSON
###EXPECTED: visually displayed, human readable error. Caused by Bad JSON.

rhtmlLabeledScatter::LabeledScatter('"{ json is fun? }"')

