// Generated by CoffeeScript 1.8.0
var SvgUtils;

SvgUtils = (function() {
  var SU, instance;

  function SvgUtils() {}

  instance = null;

  SvgUtils.get = function() {
    if (instance == null) {
      instance = new SU();
    }
    return instance;
  };

  SU = (function() {
    function SU() {}

    SU.prototype.setSvgBBoxWidthAndHeight = function(dataArray, svgArray) {
      var dataElem, i, _i, _len, _results;
      _results = [];
      for (i = _i = 0, _len = dataArray.length; _i < _len; i = ++_i) {
        dataElem = dataArray[i];
        if (!(dataElem.width != null) && !(dataElem.height != null)) {
          dataElem.width = svgArray[0][i].getBBox().width;
          _results.push(dataElem.height = svgArray[0][i].getBBox().height);
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    };

    return SU;

  })();

  return SvgUtils;

})();
