// Generated by CoffeeScript 1.8.0
var Utils;

Utils = (function() {
  var U, instance;

  function Utils() {}

  instance = null;

  Utils.get = function() {
    if (instance == null) {
      instance = new U();
    }
    return instance;
  };

  U = (function() {
    function U() {}

    U.prototype.isNum = function(num) {
      return (num != null) && typeof num === 'number';
    };

    U.prototype.isArr = function(arr) {
      return (arr != null) && arr instanceof Array;
    };

    U.prototype.isArrOfNums = function(arr) {
      return this.isArr(arr) && _.every(arr, function(n) {
        return _.isFinite(n);
      });
    };

    U.prototype.getSuperscript = function(id) {
      var digit, ss, superscript;
      superscript = [8304, 185, 178, 179, 8308, 8309, 8310, 8311, 8312, 8313];
      ss = '';
      while (id > 0) {
        digit = id % 10;
        ss = String.fromCharCode(superscript[id % 10]) + ss;
        id = (id - digit) / 10;
      }
      return ss;
    };

    U.prototype.getFormattedNum = function(num, decimals, prefix, suffix) {
      return prefix + (new BigNumber(num)).toFormat(decimals) + suffix;
    };

    return U;

  })();

  return Utils;

})();
