// Generated by CoffeeScript 1.8.0
var LabeledScatter,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

LabeledScatter = (function(_super) {
  __extends(LabeledScatter, _super);

  function LabeledScatter(width, height) {
    this.width = width;
    this.height = height;
  }

  LabeledScatter.prototype.draw = function(data, el) {
    this.data = data;
  };

  LabeledScatter.prototype.redraw = function(width, height, el) {
    this.width = width;
    this.height = height;
  };

  return LabeledScatter;

})(RhtmlStatefulWidget);
