// Generated by CoffeeScript 1.8.0
var Plot;

Plot = (function() {
  var calcViewBoxDim;

  function Plot(svg, width, height) {
    this.width = width;
    this.height = height;
    this.svg = svg;
    this.plot = this.svg.append('g').attr('class', 'plot');
  }

  Plot.prototype.updateSize = function(width, height) {};

  Plot.prototype.drawPlot = function() {
    var viewBoxDim;
    viewBoxDim = calcViewBoxDim(testData.X, testData.Y, this.width, this.height);
    return this.plot.append('rect').attr('class', 'plot-viewbox').attr('x', this.width / 4).attr('y', this.height / 4).attr('width', viewBoxDim.width).attr('height', viewBoxDim.height).attr('fill', 'none').attr('stroke', 'black').attr('stroke-width', '1px');
  };

  calcViewBoxDim = function(X, Y, width, height) {
    return {
      width: width / 2,
      height: height / 2,
      rangeX: Math.max.apply(null, X) - Math.min.apply(null, X),
      rangeY: Math.max.apply(null, Y) - Math.min.apply(null, Y)
    };
  };

  return Plot;

})();
